In [1]:
import pandas as pd
data = pd.read_excel("../Data/Folkhalsomyndigheten_Covid19.xlsx", sheet_name="Veckodata Riket") 

print(data.head(10))

     år  veckonummer  Antal_fall_vecka  Antal_fall_100000inv_vecka  \
0  2020            6                 1                           0
1  2020            7                 0                           0
2  2020            8                 0                           0
3  2020            9                13                           0
4  2020           10               211                           2
5  2020           11               838                           8
6  2020           12               924                           9
7  2020           13              1957                          19
8  2020           14              3229                          31
9  2020           15              3740                          36

   Antal_fall_100000inv_14dagar  Kum_antal_fall  Kum_fall_100000inv  \
0                             0               1                   0
1                             0               1                   0
2                             0               1                   0
3                             0              14                   0
4                             2             225                   2
5                            10            1063                  10
6                            17            1987                  19
7                            28            3944                  38
8                            50            7173                  69
9                            67           10913                 106

   Antal_nyaintensivvårdade_vecka  Kum_antal_intensivvårdade  \
0                               0                          0
1                               0                          0
2                               0                          0
3                               0                          0
4                               3                          3
5                              16                         19
6                              88                        107
7                             238                        345
8                             277                        622
9                             289                        911

   Antal_avlidna_vecka  Antal_avlidna_milj_inv_vecka  Kum_antal_avlidna  \
0                    0                      0.000000                  0
1                    0                      0.000000                  0
2                    0                      0.000000                  0
3                    0                      0.000000                  0
4                    0                      0.000000                  0
5                    5                      0.500000                  5
6                   44                      4.300000                 49
7                  190                     18.400000                239
8                  451                     43.700001                690
9                  664                     64.300003               1354

   Kum_antal_avlidna_milj_inv
0                    0.000000
1                    0.000000
2                    0.000000
3                    0.000000
4                    0.000000
5                    0.500000
6                    4.700000
7                   23.100000
8                   66.800003
9                  131.100006

In [2]:
c19_num_cases = pd.read_excel('../Data/Folkhalsomyndigheten_Covid19.xlsx', sheet_name="Antal per dag region")   # Reads excel, and checks the "Antal per dag region" column
c19_num_cases.head(5)

,Statistikdatum,Totalt_antal_fall,Blekinge,Dalarna,Gotland,Gävleborg,Halland,Jämtland_Härjedalen,Jönköping,Kalmar,...,Stockholm,Sörmland,Uppsala,Värmland,Västerbotten,Västernorrland,Västmanland,Västra_Götaland,Örebro,Östergötland
0,2020-02-04,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-02-05,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2020-02-06,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-02-07,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-02-08,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
c19_num_cases = c19_num_cases[["Statistikdatum", "Västra_Götaland"]]        # Opens Statistikdatum, and Västra_Götaland columns, as displayed below
c19_num_cases

    Statistikdatum  Västra_Götaland
0       2020-02-04                0
1       2020-02-05                0
2       2020-02-06                0
3       2020-02-07                0
4       2020-02-08                0
..             ...              ...
991     2022-10-22               29
992     2022-10-23               11
993     2022-10-24               38
994     2022-10-25               86
995     2022-10-26               75

[996 rows x 2 columns]

In [4]:
fig = sns.lineplot(                                                     # trying out seaborn to print a lineplot
    data=c19_num_cases,                                                 # sets the data to be taken from our dataframe
    x="Statistikdatum",                                                 # locates "Statistikdatum", and assigned it to the x label
    y="Västra_Götaland",                                                # locates "Västra_Götaland", and assigns it to the y label 
)

fig.set(
    title="Number of daily Covid-19 cases in Västra Götaland",          # displays title above the line 
    xlabel="",                                                          # instead of typing individual values, we pull all "Statistikdatum" into x & y
    ylabel=""
    
)
plt.xticks(fontsize=7, rotation=90)                                    # Suggested by Anna-Maria, to prevent the dates from colliding
fig = fig.get_figure() 
fig.savefig("Visualiseringar/KPI2_Daily_Cases_Vastra_Gotaland.png")     # exports the image

NameError: name 'sns' is not defined

In [5]:
import pandas as pd
import os

class OlympicsData:
    def __init__(self, data_folder_path: str) -> None:
        #self._data =  pd.read_csv("./Data/athlete_events.csv") 
        self._data_folder_path = data_folder_path
        
    def olympics_dataframe (self, olympicsname: str) -> list:
        olympics_df_list = []
        
        for path_ending in ["Covid19.xlsx"]:
            path = os.path.join(self._data_folder_path, olympicsname + path_ending)
            
            olympic = pd.read_csv(path)
            #olympics_df_list.append(olympic)
        return olympic